### ISSUE TITLE
preflight fails on "operator-sdk scorecard: unexpected end of JSON input"

### ISSUE THREAD

**Issue by jbattiato** [redhat-openshift-ecosystem/openshift-preflight#1203]
## Bug Description

The `preflight check operator` command fails to read the `scorecard` output with the following error:

```
time="2024-10-02T15:57:04+02:00" level=info msg="running scorecard with the following invocation" args="[\"operator-sdk\",\"scorecard\",\"--output\",\"json\",\"--selector=test=basic-check-spec-test\",\"--kubeconfig\",\"/tmp/2804899030\",\"--wait-time\",\"240s\",\"--namespace\",\"default\",\"--service-account\",\"default\",\"--config\",\"/tmp/scorecard-test-config-798981960.yaml\",\"--verbose\",\"/tmp/preflight-3318550770/fs\"]"
time="2024-10-02T15:57:04+02:00" level=info msg="check completed" check=ScorecardBasicSpecCheck err="failed to run operator-sdk scorecard: unexpected end of JSON input" result=ERROR
```

## Version and Command Invocation

1.10.0

```
ime="2024-10-02T12:24:50Z" level=info msg="certification library version" version="1.10.0 <commit: c9048da99aae76ddee5a708edcc94e14c034cd1d>"
```

## Steps to Reproduce:
```
PFLT_INDEXIMAGE=<index-image> PFLT_ARTIFACTS=preflight_results  KUBECONFIG=${HOME}/.kube/config \
  ./preflight check operator <bundle-image>  --docker-config ${HOME}/.docker/config.json
```

I'm sorry, I'm working on a closed fork of [cloudnative-pg](https://github.com/cloudnative-pg/cloudnative-pg), and I can't share the associated workflow output.

## Expected Result
preflight should be able to read the scorecard JSON output since the latter is well formed when running it standalone:

```
./operator-sdk scorecard <bundle-image> --wait-time 60s --output json > scorecard.json
jq -e . >/dev/null 2>&1 <<<$(cat scorecard.json)
echo $?
0
```

## Actual Result

These errors from `ScorecardBasicSpecCheck` and `ScorecardOlmSuiteCheck`:

```
level=info msg="check completed" check=ScorecardBasicSpecCheck err="failed to run operator-sdk scorecard: unexpected end of JSON input" result=ERROR
```
```
level=info msg="check completed" check=ScorecardOlmSuiteCheck err="failed to run operator-sdk scorecard: unexpected end of JSON input" result=ERROR
```

## Additional Context

The error itself is not very informative, and I couldn't find any clues on the root cause behind the preflight fail.

Related code:
https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/c9048da99aae76ddee5a708edcc94e14c034cd1d/internal/operatorsdk/operatorsdk.go#L102

https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/c9048da99aae76ddee5a708edcc94e14c034cd1d/internal/operatorsdk/operatorsdk.go#L112

I looked up the `"failed to run operator-sdk scorecard: unexpected end of JSON input"` error in the issues and found this: https://github.com/redhat-openshift-ecosystem/openshift-preflight/issues/355

I might be wrong, but it does not feel to be related.

Can you help me investigating this issue?

**Comment by acornett21** [comment]
Hi @jbattiato What version of operator sdk are you use? Can you share the scorecard directory? There really isn't anything in this issue where we could replicate/troubleshoot this.

**Comment by jbattiato** [comment]
> Hi @jbattiato What version of operator sdk are you using? Can you share the scorecard directory? There really isn't anything in this issue where we could replicate/troubleshoot this.

I'll try to collect and share to you as much as possible.
Thanks for looking into this already!

**Comment by acornett21** [comment]
If you can at least share the scorecard `config.yaml` I can plug that into a public bundle and replicate. For clarity I'm talking about this file.

https://github.com/redhat-openshift-ecosystem/certified-operators/blob/main/operators/cloudnative-pg/1.24.0/tests/scorecard/config.yaml

**Comment by jbattiato** [comment]
This `preflight check` command uses the open source image:

```
PFLT_ARTIFACTS=preflight_operator_results \
  BUNDLE_IMG=ghcr.io/cloudnative-pg/cloudnative-pg-testing:bundle-cnp-5405 \
  PFLT_INDEXIMAGE=ghcr.io/cloudnative-pg/cloudnative-pg-testing:index-cnp-5405 \
  KUBECONFIG=~/.kube/config \
  bin/preflight check operator ghcr.io/cloudnative-pg/cloudnative-pg-testing:bundle-cnp-5405  --loglevel trace
```

The scorecard will be shown in the preflight output.

scorecard config:

```
apiVersion: scorecard.operatorframework.io/v1alpha3
kind: Configuration
metadata:
  name: config
stages:
- parallel: true
  tests:
  - entrypoint:
    - scorecard-test
    - basic-check-spec
    image: quay.io/operator-framework/scorecard-test:v1.37.0
    labels:
      suite: basic
      test: basic-check-spec-test
  - entrypoint:
    - scorecard-test
    - olm-bundle-validation
    image: quay.io/operator-framework/scorecard-test:v1.37.0
    labels:
      suite: olm
      test: olm-bundle-validation-test
  - entrypoint:
    - scorecard-test
    - olm-crds-have-validation
    image: quay.io/operator-framework/scorecard-test:v1.37.0
    labels:
      suite: olm
      test: olm-crds-have-validation-test
  - entrypoint:
    - scorecard-test
    - olm-crds-have-resources
    image: quay.io/operator-framework/scorecard-test:v1.37.0
    labels:
      suite: olm
      test: olm-crds-have-resources-test
  - entrypoint:
    - scorecard-test
    - olm-spec-descriptors
    image: quay.io/operator-framework/scorecard-test:v1.37.0
    labels:
      suite: olm
      test: olm-spec-descriptors-test
  - entrypoint:
    - scorecard-test
    - olm-status-descriptors
    image: quay.io/operator-framework/scorecard-test:v1.37.0
    labels:
      suite: olm
      test: olm-status-descriptors-test
```
