### ISSUE TITLE
[Disconnected env] Have --config flag to be exposed by preflight to allow custom config for scorecard

### ISSUE THREAD

**Issue by tkrishtop** [redhat-openshift-ecosystem/openshift-preflight#276]
## Is your feature request related to a problem? Please describe.
Preflight automatically generates operator-sdk scorecard config `scorecard-test-config.yaml` which contains images like `quay.io/operator-framework/scorecard-test:master`.
I work from disconnected environment where I can't pull external-registry images, I always have to pull from my local registry. 

## Describe the solution you'd like.
I'd like to have a way to pass my custom config into scorecard. Or, at least to pass my local-registry scorecard images. 
[Here is how that could be done when using scorecard directly](https://github.com/redhat-cip/ansible-role-dci-cvp/blob/e91ba3f512dbfbfabafa82720632d75f6b43a76e/tasks/mirror_bundle.yml#L48)

## Describe alternatives you've considered.
To have this feature is mandatory to run scorecard inside preflight in disconnected environments.

**Comment by komish** [comment]
For context - here are the current Scorecard-related checks we use today:

- ScorecardBasicSpecCheck
- ScorecardOlmSuiteCheck

These are two of the built-in checks made available in the provided Scorecard image `quay.io/operator-framework/scorecard-test`, executed individually to comply with Preflight's approach to executing these tests. 

I'm not sure it makes sense for preflight to accept an arbitrary scorecard configuration to accomplish these two checks, as I'm thinking this could break the execution by (a) allowing a user to circumvent them, auto-pass them, etc, (b) leave out these scorecard tests, causing the preflight check for them to just fail.

I _think_ allowing the user to change the image also carries similar implications.

@samira-barouti @bcrochet thoughts on the above?

---

@tkrishtop  On the other hand, is there any way to include the default scorecard images as mirror targets in disconnect environments? It should be relatively reasonable to refer to scorecard images by digest in our generated configuration.

I only have partial understandings of the requirements for disconnected envs, so pardon any ignorance on my end!

**Comment by tkrishtop** [comment]
> @tkrishtop On the other hand, is there any way to include the default scorecard images as mirror targets in disconnect environments? It should be relatively reasonable to refer to scorecard images by digest in our generated configuration.

Hi @komish thank you for the reply. 
Yes, we could have scorecard images to be downloaded from local registry by using imageContentSourcePolicy. For that, we'd need two things:
- to have a way to retrieve preflight scorecard config (to extract a list of scorecard images to mirror), or to get directly the list of scorecard images to mirror
- the scorecard images in the config should use sha and not tags, i.e. something like this:

```
apiVersion: scorecard.operatorframework.io/v1alpha3
kind: Configuration
metadata:
  name: config
stages:
- parallel: true
  tests:
  - entrypoint:
    - scorecard-test
    - basic-check-spec
    image: quay.io/operator-framework/scorecard-test@sha256:a19108b15632921434b853447435db666b81ecd2c1b327668b2f3d836a7bdbee
    labels:
      suite: basic
      test: basic-check-spec-test
  - entrypoint:
    - scorecard-test
    - olm-bundle-validation
    image: quay.io/operator-framework/scorecard-test@sha256:a19108b15632921434b853447435db666b81ecd2c1b327668b2f3d836a7bdbee
    labels:
      suite: olm
      test: olm-bundle-validation-test
```

and not `quay.io/operator-framework/scorecard-test:master`
